
name: teste

on:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  GET_DOCKER_USR: ${{ vars.DOCKER_USR }}

jobs:
  afere_variavel:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret
        continue-on-error: true
        env:
          MY_SECRET: ${{ secrets.TK_GITHUB_REGISTRY }}
        if: ${{ env.MY_SECRET == '' }}
        run: echo "MY_SECRET não existe"

      - name: Secret not found
        env:
          MY_SECRET: ${{ secrets.TK_GITHUB_REGISTRY }}
        if: ${{ env.MY_SECRET != '' }}        
        run: echo "MY_SECRET existe"


      - name: Teste de atribuicao
#        env:
        run: echo Teste de atribuicao 1030

      - name: Teste de atribuicao II
        continue-on-error: true
        env:
          VAR: ${{ vars.DOCKER_USR }}
        run: echo $VAR | sha256sum

      - name: Teste de atribuicao III
        continue-on-error: true
        env:
          VAR: ${{ vars.GET_DOCKER_USR }}
        run: echo $VAR