
name: teste-disabled

on:
  push:
    branches:
      - main-disabled

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  GET_DOCKER_USR: ${{ vars.DOCKER_USR }}

jobs:
  afere_variavel:
    runs-on: ubuntu-latest
    steps:
      - name: List all env vars
        run: printenv

      - name: Set Environment
        id: env-setup        
          run: echo "DOCKER_TAG=${{ vars.DOCKER_USR }} >> "$GITHUB_ENV"