
name: teste

on:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  GET_DOCKER_USR: ${{ vars.DOCKER_USR }}
jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: rodrigorootrj/operator-echo-sha256:latest

    steps:
      - run: ./operador.sh foobar 