
name: teste

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Login Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.DOCKER_USR }}
          password: ${{ secrets.TK_GITHUB_REGISTRY }}

      - name: Run container
        run: docker run ghcr.io/rodrigorootrj/operator-echo-sha256:latest foobar