
name: teste

on:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  GET_DOCKER_USR: ${{ vars.DOCKER_USR }}
jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Login GHCR
        run: |
          echo "${{ secrets.TK_GITHUB_REGISTRY }}" | \
            docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Run container
        run: docker run rodrigorootrj/operator-echo-sha256:latest foobar