
name: teste-mod-02

on:
  push:
    branches: mod-01

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Test secret
        env:
          TOKEN: ${{ secrets.TK_GITHUB_REGISTRY_3 }}
        run: |
          if [ -z "$TOKEN" ]; then
            echo "SECRET VAZIO"
            exit 1
          fi

          echo "SECRET EXISTE"    